name: Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Imprimir en consola
        run: echo "Hello World, GITHUB ACTIONS."

  test:
    needs: helloworld
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Instalar dependencias y pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest requests

      - name: Test FastAPI
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
          DB_NAME: ${{ secrets.DB_NAME }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          FIREBASE_CREDENTIALS_BASE_64: ${{ secrets.FIREBASE_CREDENTIALS_BASE_64 }}
        run: |
          python -m pytest -v test_database.py

  deploy: 
    needs: test   
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Railway CLI
        run: |
         # Método oficial con retry
         curl -sSfL https://railway.app/install.sh | sh || {
         echo "Primer intento fallido, usando método alternativo..."
         curl -L https://github.com/railwayapp/cli/releases/latest/download/railway-linux-x86_64 -o railway
         chmod +x railway
         sudo mv railway /usr/local/bin/
         }


      - name: Add Railway CLI to PATH
        run: |
          if [ -d "$HOME/.railway/bin" ]; then
            echo "$HOME/.railway/bin" >> $GITHUB_PATH
            export PATH="$HOME/.railway/bin:$PATH"
          fi

      - name: Verify Railway CLI installation
        run: |
          railway --version || railway version || echo "Railway CLI installation failed"

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          echo "Starting deployment..."
          railway up --service "videojuego-api" || \
          railway up --service "api" || \
          railway up --service "web" || \
          (echo "No service found, creando uno nuevo..." && railway up)

      - name: Health check
        env:
          SERVICE_URL: ${{ secrets.RAILWAY_SERVICE_URL }} 
        run: |
          echo "Checking /health endpoint..."
          for i in {1..10}; do
            status=$(curl -s -o /dev/null -w "%{http_code}" $SERVICE_URL/health)
            echo "Attempt $i: status=$status"
            if [ "$status" == "200" ]; then
              echo "Service is healthy!"
              exit 0
            fi
            sleep 10
          done
          echo "Service failed health check"
          exit 1
