name: Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  helloworld:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Imprimir en consola
        run: echo "Hello World, GITHUB ACTIONS."

  test:
    needs: helloworld
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Test FastAPI
        env: 
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
          DB_NAME: ${{ secrets.DB_NAME }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          FIREBASE_CREDENTIALS_BASE_64: ${{ secrets.FIREBASE_CREDENTIALS_BASE_64 }}
        run: |
          pytest -v test_database.py
